server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    #表示本引用是否是向注册中心注册自己（配置高可用的时候需要设置为true，也就是默认值）
    registerWithEureka: false
    #是否去检索服务
    fetchRegistry: false
    serviceUrl:
      #eureka服务地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/